### ISSUE TITLE
Logging into On Board Hive through Hive Keychain?

### ISSUE THREAD

**Issue by Zerophase** [stoodkev/hive-keychain#100]
I'd like to invite some people to Hive through a referral link. But, it requires me to paste a private key in. I don't feel comfortable putting that online. Is there any means the Hive Keychain can log me in? 

I'm used to other cryptocurrencies where you keep your private keys offline at all times.
Is there a better solution than bringing my private key online? Is there a private key with limited access that would work for this?

**Comment by stoodkev** [comment]
Hi! You're definitely right and should avoid pasting your keys online at
all cost.  Whether the process can use Hive Keychain  would depend on the
dApp integration. Which one are you using ?

**Comment by Zerophase** [comment]
I'm trying to login to [Hive Onboard ](https://hiveonboard.com/what-is-hive)to give out referral links to people that I think might benefit from the platform. This is the [login](https://hivesigner.com/import?client_id=hiveonboard&redirect_uri=http%3A%2F%2Fhiveonboard.com%2Fdashboard&scope=login) they're using.

**Comment by Zerophase** [comment]
Ok, I figured out I can do it directly through Peakd. I feel like some of the Hive dapps need a little redesign to be secure.
