### ISSUE TITLE
Option to inject keychain only to list of preallowed websites.

### ISSUE THREAD

**Issue by remirafun** [stoodkev/hive-keychain#101]
According to the docs, the extension injects itself into every website. It would be a good to add an option/make it default to inject the extension only to websites allowed by a user. This way, websites that do not have the access will not be able to track who has the extension installed. Moreover, the extension will not unnecessarily slow down user's browser. From the user perspective, the user will simple once add a website to a list if he chooses to use this option once and enjoy increased benefits of privacy.

**Comment by stoodkev** [comment]
Making it the default would make the extension much less user friendly for most of users.
The code injected is extremely light so I believe the proportion in which it would slow down a browser is insignificant, almost all of the heavy lifting happens on the background, which is independent of the number of open tabs.
I'll leave it open in case someone wants to work on this once the refactor is done, but I'm not ready to commit resources for this now, we have a lot going on.

**Comment by remirafun** [comment]
Okay, thank you for your reply. Also users, for now, have the option to use a separate browser profile with the extension to achieve similar purpose.
