### ISSUE TITLE
Loss of hive token

### ISSUE THREAD

**Issue by Tankd4fish4373** [stoodkev/hive-keychain#105]
I purchased hive token on binance , transfered it to hive keychain  converted it to  hive dollars,fine, went to convert it back to hive and its disapeared ?

**Comment by stoodkev** [comment]
Conversions take 3.5 days to process. Your tokens are not lost.

**Comment by Tankd4fish4373** [comment]
Thats great thank you for clarifying that for me quickly.

**Comment by Tankd4fish4373** [comment]
Resoved thank you.
