### ISSUE TITLE
requestHandshake callback returning undefined

### ISSUE THREAD

**Issue by JenyaFTW** [stoodkev/hive-keychain#108]
Trying to check whether Hive Keychain is installed (which it is) by doing requestHandshake, like this:

`
window.hive_keychain.requestHandshake(res => {
  console.log(res); // undefined
});
`

However, it is returning undefined.

**Comment by stoodkev** [comment]
The handhsake callback doesn't have arguments, so it's normal it's returning undefined.
The fact that the callback is triggered at all means that Keychain is installed.
