### ISSUE TITLE
query: how can I use this for backend(node js). I want to transfer tokens

### ISSUE THREAD

**Issue by aster2709** [stoodkev/hive-keychain#109]
Hey awesome wallet. My use case is to transfer 'x' tokens from user in the backend. I'm able to use the package in frontend ofcourse doing `requestSendToken`. how can this be achieved in nodejs? I understand that I'd need the users keys but what are the calls. 

thanks alot!

**Comment by sn0n** [comment]
https://developers.hive.io/apidefinitions/#broadcast_ops_transfer

**Comment by stoodkev** [comment]
Indeed, as @sn0n mentioned above, you should rather check hive dev documentation, since on the backend side you cannot use Keychain.
Actually, you don't necessarily need the user key to do this. An alternative way is to use the `add_account_authority` operation, in order to whitelist an account to be able to broadcast on behalf of user accounts.
That being said, transfers require active authority, and I doubt anyone would be willing to giving active authority to a third-party since it would enable to transfer out the account holdings.

**Comment by sn0n** [comment]
Another sidenote on that note,.. 

I think the way most services working with transfers on hive are streaming blocks on the backend looking for transfers to go through, and handling the actual transfer off to the customers choice of app.

**Comment by aster2709** [comment]
hey guys, I just said `user` on a whim. but its going to be me. I'm wanting to transfer tokens in backend. the `transfer` operation says you can only transfer `HIVE` or `HBD`? would it work for tokens like SPS, etc etc

**Comment by sn0n** [comment]
> hey guys, I just said `user` on a whim. but its going to be me and my key only. I'm wanting to transfer tokens in backend. the `transfer` operation says you can only transfer `HIVE` or `HBD`? but I am needing to transfer tokens like SPS, etc etc

That would be using hive engine, their website ( https://hive-engine.com/?p=faq ) references: https://github.com/harpagon210/sscjs

**Comment by aster2709** [comment]
thanks sir. i looked into the hive-engine `sscjs ` package. the docs aren't clear on how to do that. but thanks for the leads, I'll take it there as it my issue doesn't deal with hive-keychain :+1:

**Comment by aster2709** [comment]
hey @sn0n @stoodkev the hive-engine doesn't have much for dev support. keychain also does hive engine token transfers, so how do u guys do it? I'll read into it thanks!

**Comment by sn0n** [comment]
Their discord is probably the best bet: https://discord.gg/xWRYB9s

**Comment by stoodkev** [comment]
You need to broadcast a json with this format : 

```
const id = CHAIN_ID;
  const json = {
    contractName: "tokens",
    contractAction: "transfer",
    contractPayload: {
      symbol: token,
      to: account_to,
      quantity: amount,
      memo: memo,
    },
  };
```

**Comment by aster2709** [comment]
thanks sirs!
