### ISSUE TITLE
How do you retrieve the Hive / HBD balance?

### ISSUE THREAD

**Issue by Wend1go** [stoodkev/hive-keychain#110]
Browsing the docs in the Readme.md, I couldn't find any information about how to access information about the logged in Hive account.
Could you give me an example about how to retrieve the Hive / HBD balance of an account please?

**Comment by stoodkev** [comment]
Hi! Hive Keychain is a wallet, for what you want, you need to use Hive js libraries, dHive or Hive-js.
I recommend dHive because it is typed : https://openhive-network.github.io/dhive/

**Comment by Wend1go** [comment]
Thanks, I'll have a look. 👍
