### ISSUE TITLE
Version 1.8.2.4 is not working for me

### ISSUE THREAD

**Issue by bala41288** [stoodkev/hive-keychain#23]
I tried downloading the latest package and installed the package. None of the requests went through. window.hive_keychain says the Hive Keychain is not installed. 

I had to then remove the extension and use the previous version which was 1.8.2.1 which works fine with a few issues.

**Comment by VIM-Arcange** [comment]
@bala41288 A new version 1.8.2.5 has been released. Can you retry with this one?
