### ISSUE TITLE
Uncaught SyntaxError: await is only valid in async function

### ISSUE THREAD

**Issue by gadrian78** [stoodkev/hive-keychain#33]
I receive this error in developer mode, after I load the packed extension:
![image](https://user-images.githubusercontent.com/31955497/79068446-91897280-7ccf-11ea-911d-90264ec9c647.png)

Keychain extension (0.18.2.5) works for me though, other than claiming account ticket tokens, the issue I also describe [here](https://peakd.com/hive-175001/@gadrian/having-trouble-claiming-account-tickets).

I have an Opera browser, use Install Google Extensions extension. Had no similar issues with Steem Keychain.

**Comment by VIM-Arcange** [comment]
This code is not from the master branch.  Code from other branches is **not** considered stable and should not be used in production.
Please download and update your Keychain extension from the **master** branch
