### ISSUE TITLE
How to upgrade without export and import?

### ISSUE THREAD

**Issue by brianoflondon** [stoodkev/hive-keychain#34]
Is there a way to upgrade the extension without exporting all keys and importing them?

I'm using Brave, would be good if instructions on upgrading could be added to the Readme.

I'm on version 1.8.1 but I've got 1.8.2.5 I think downloaded.

**Comment by VIM-Arcange** [comment]
Upgrade should be automatic once Google will approve the extension and publish it on Webstore
Meantime, simply download the zip file and extract it into the existing extension directory. There is no need to export/import.
