### ISSUE TITLE
Unable to unvote witnesses

### ISSUE THREAD

**Issue by themarkymark-steem** [stoodkev/hive-keychain#4]
All witnesses show as disabled, I am unable to remove any of them. 

![](https://i.imgur.com/oezLOLx.png)

Using the latest version Hive branch and pointing to Anyx node.

**Comment by stoodkev** [comment]
Oops yeah I need to implement hivesql on our backend to get the right info
asap

**Comment by stoodkev** [comment]
This has been fixed in a previous release.
