### ISSUE TITLE
Hive Keychain extension not installed despite already setup manually.

### ISSUE THREAD

**Issue by chinwei1989** [stoodkev/hive-keychain#40]
` if (window.hive_keychain) {
            console.log('Hive Keychain extension installed');
        } else {
            console.log('Hive Keychain extension not installed 2');
        }`

I'm not able to call launch Hive Keychain extension despite i have it installed. Above handshake code is telling my Hive keychain extension not installed. Any idea what happen? I already pull  the latest code.  
I can see the Hive Keychain icon available  on my browser top right. But the hive_keychain.requestTransfer wasn't working.

**Comment by stoodkev** [comment]
Are you running 1.8.3?

**Comment by stoodkev** [comment]
You can use Hive Keychain directly from the Chrome Store now :
https://chrome.google.com/webstore/detail/hive-keychain/jcacnejopjdphbnjgfaaobbfafkihpep
