### ISSUE TITLE
Cannot manage ninth account above.

### ISSUE THREAD

**Issue by puncakbukit** [stoodkev/hive-keychain#41]
![image](https://user-images.githubusercontent.com/26822588/79628397-9d67af80-817b-11ea-8792-d5546269cfca.png)

Only eight accounts are visible, so we cannot manage ninth account  above.
How can we do?

**Comment by VIM-Arcange** [comment]
Use the mouse wheel to scroll down and display other accounts

**Comment by brianoflondon** [comment]
How funny. I never noticed that there wasn't a scroll bar on the side!

**Comment by puncakbukit** [comment]
Thank you!! Since my laptop uses touchpad, I never thought about the wheel.
After plugged a mouse and use the wheel, now I can see the other accounts.. :-)
