### ISSUE TITLE
Encrypting A Memo Without Sending a Transaction?

### ISSUE THREAD

**Issue by Snaddyvitch-Dispenser** [stoodkev/hive-keychain#43]
Hello There,

I am currently trying to encrypt an exchange (within a custom_json) by using a user's Memo key (from) to send an encrypted message to the recipient. Is there any way to do this with Keychain or do I need to ask my users for their memo key (I *really* don't want to do that)

Thanks!

**Comment by stoodkev** [comment]
This has not been implemented yet.
I ll try to take care of it when I m done with the current features.

**Comment by Snaddyvitch-Dispenser** [comment]
Thank you very much. It'll be great to keep the users keys within keychain only and means people won't have to trust me.

Many thanks, much appreciated!

**Comment by VIM-Arcange** [comment]
When implemented, this feature should allow choosing which key is used for the encryption, not only the memo key.

**Comment by stoodkev** [comment]
> When implemented, this feature should allow choosing which key is used for the encryption, not only the memo key.

Yes, ofc.

**Comment by Snaddyvitch-Dispenser** [comment]
Hey there, sorry to bother you, but any updates on this feature?

**Comment by stoodkev** [comment]
Yes, it is pending review, I will make an announcement when it's pushed to the store.
In the meantime, you can check it on the `dev` branch.

**Comment by Snaddyvitch-Dispenser** [comment]
Awesome, thanks!
