### ISSUE TITLE
Firefox support?

### ISSUE THREAD

**Issue by Snaddyvitch-Dispenser** [stoodkev/hive-keychain#5]
I know this is early days, but will firefox support come soon, or am I best to switch browsers?

**Comment by stoodkev** [comment]
Hi Conor,
You can already install it locally in dev mode in your Firefox browser.
We will push it to the store as well when stable.

**Comment by clarkphp** [comment]
There is some advice in the comment at https://peakd.com/hive/@okean123/re-moon32walker-q7idzn, but I'm not quite there, yet, myself, on FF ESR 68.0.

For context, the parent post is here: https://peakd.com/hive/@okean123/how-to-install-hive-keychain-from-github

**Comment by Snaddyvitch-Dispenser** [comment]
Thanks for the information, Quentin. The plugin is loaded and now I can go back to my old ways 😆

Many thanks for all the work you do towards the plugin, too!

Also, thanks Clark for the information.
