### ISSUE TITLE
Login with keychain does not allow account_update2

### ISSUE THREAD

**Issue by Jrejoire** [stoodkev/hive-keychain#51]
When signing in with Hivekeychain the user only has 'login' scope which does not allow profile update (account_update2). It works fine when using hivesigner. Not sure how to fix this. Any help is welcome.

![Capture](https://user-images.githubusercontent.com/33304306/81811122-6ab79980-9524-11ea-8c0a-d2c717c1fad1.png)
![Capture2](https://user-images.githubusercontent.com/33304306/81811128-6c815d00-9524-11ea-8be4-1dde49a55230.png)

**Comment by stoodkev** [comment]
Hi @Jrejoire  and sorry for late answer, do you still have this issue? 
If yes can you give me a bit more context so I can try and help you?
The easiest way to broadcast an accout_update2 via Keychain would probably be to request it as a generic broadcast.

**Comment by Jrejoire** [comment]
Thanks for the response. I had left keychain login aside for now. I'll try adding it again with the generic broadcast for accout_update2.
