### ISSUE TITLE
All wallets should check against blacklist before transfer to save users from losing funds

### ISSUE THREAD

**Issue by dnotestein** [stoodkev/hive-keychain#52]
@brianoflondon just lost funds sending to bloctrades instead of blocktrades using keychain. It's really important that wallets use the blacklist of phishing account names to avoid such losses. Please add this on a priority basis to avoid further fund losses (I just realized I should create a similar isssue for the hive cli wallet).

**Comment by brianoflondon** [comment]
Yup, not looking for anybody's sympathy, but just to help other's avoid this kind of thing and make the whole system safer.

**Comment by stoodkev** [comment]
@dnotestein where can I find this list? I ll implement it asap

**Comment by VIM-Arcange** [comment]
https://gitlab.syncad.com/hive/condenser/-/blob/develop/src/app/utils/BadActorList.js
