### ISSUE TITLE
Error when displaying broadcast operation details

### ISSUE THREAD

**Issue by VIM-Arcange** [stoodkev/hive-keychain#62]
When broadcasting operations and clicking on the "click to show" link in the confirmation dialog, the details are displayed (scroll down) then immediately hidden (scroll up)

![image](https://user-images.githubusercontent.com/21260036/91566075-6c766300-e943-11ea-83e0-750f7950f119.png)

Keychain v1.10

**Comment by stoodkev** [comment]
I have tested this on Chrome, Opera and FF and cannot reproduce the issue.

**Comment by VIM-Arcange** [comment]
Really strange, I did the test again today and now it's working correctly.
I will reopen the issue if it reappears.
