### ISSUE TITLE
Create a login form

### ISSUE THREAD

**Issue by mojosef** [stoodkev/hive-keychain#76]
Hi Everyone

This is more of a question than an issue. I'm trying to figure out a way to create a login form using hive keychain, similar to what is on here https://hive-engine.com/?p=sign_in. Can anyone point me in the right direction?

Thanks in anticipation

**Comment by stoodkev** [comment]
You can use [requestSignBuffer](https://github.com/stoodkev/hive-keychain#requestsignbuffer) and then check that the signature is correct and belongs to the user.

**Comment by therealwolf42** [comment]
It would be really nice to have the username optional and have the user enter/select the account themselves. As I would prefer not to have to add an input field for the username.
