### ISSUE TITLE
Confirm transaction dialogue hidden and inaccessible in Brave

### ISSUE THREAD

**Issue by kendewitt** [stoodkev/hive-keychain#86]
When using Hive Keychain to login or perform other transactions with Brave browser in full screen mode, the confirm transaction pop-up gets hidden and is inaccessible. Only option is to refresh screen, take Brave out of full screen mode, and redo the transaction. This happens on my Macbook running Mojave.

**Comment by stoodkev** [comment]
I've tested on Brave on Big Sur in full screen mode and I cannot reproduce this behavior. When the popup appears it minimizes the page in full screen and when I click to return on Brave it shows both the dApp and the Keychain window.
In any case, this is about the way your browser handles popups and the way your Mac handles full screen, there's nothing I can do about this behavior.
