### ISSUE TITLE
Unable to export keys from keychain on chrome Mac

### ISSUE THREAD

**Issue by dm312-1** [stoodkev/hive-keychain#90]
I am trying to switch browsers from chrome to Brave and I am unable to export the files. Chrome shows a download, but nothing happens and does not show up in the downloads folder Mac

**Comment by stoodkev** [comment]
Can you please check if you can download files without issues from your
browser? I ve got a similar issue before but it turned out it was a
browser issue after an update.
I've tested it and it's working fine on my end on both Chrome and Brave
(Mac).

**Comment by dm312-1** [comment]
I figured out what happened. I had to disable ask where to download on chrome.
