### ISSUE TITLE
Peakd Community account handler (for posting keys)

### ISSUE THREAD

**Issue by 4Ykw** [stoodkev/hive-keychain#94]
When trying to use peakd for example, to manage a community account (for the very rare common case of adding another admin for example), peakd asks for posting key, which is not populated on the hivekeychain slot. Hence the request fails.

Confused if the case is because there should be no posting key or because the fact the posting key is the same as the active key, the active key is not being interpreted as being the one that should be used for posting actions.

More clarification might be needed, but I can replicate the problem.

**Comment by stoodkev** [comment]
I'm a bit confused, why not entering your posting key on Keychain if you want to perform actions that need posting authority?

**Comment by 4Ykw** [comment]
It does not allow it to do it right now. It identifies it as being already inserted on the (in this particular case for community accounts) active key. This might be because the posting and active keys on the community accounts are the same or because there are no posting auths in communities accounts (I have not checked this) and hence the active key should be used for posting activities.

**Comment by 4Ykw** [comment]
If you add a posting key as the same as the active key it will complain, saying that its not the posting key:

![image](https://user-images.githubusercontent.com/6281545/122243630-62484400-cf18-11eb-8120-7f87baf1a1cd.png)

![image](https://user-images.githubusercontent.com/6281545/122244075-b2bfa180-cf18-11eb-92d7-e1e26193135f.png)

**Comment by 4Ykw** [comment]
Ok, had a look at the code and this function might be the reason why it's failing and then jumping into the last else...

![image](https://user-images.githubusercontent.com/6281545/122246593-c8ce6180-cf1a-11eb-85b2-70eba5fb24e7.png)

**Comment by stoodkev** [comment]
Well I have looked at that particular account on hiveblocks, and public posting and active keys are different, so the private keys should be different as well. You can test it by removing the active key and try to add the posting key again, if I´m right, it still wont work because your posting key is different.

**Comment by 4Ykw** [comment]
Damn... you right. This is an ecency bug when creating the community. Its providing the posting key as the same as the active key. Will reach them out. Thanks.
