### ISSUE TITLE
Add account menu (after signing a transaction for the community creation) showing posting key as the same as active key

### ISSUE THREAD

**Issue by 4Ykw** [stoodkev/hive-keychain#96]
After finding out more information about what led me to open https://github.com/stoodkev/hive-keychain/issues/94, I have tested the process once more with ecency + keychain and found out that the issue is being caused somewhere before or at the new account (in this case a community account specifically) is being asked to be added to Hive Keychain.

![image](https://user-images.githubusercontent.com/6281545/122477797-6d849800-d01c-11eb-8726-3d2417372c87.png)

So, I am trying to understand what part of the code deducts those private keys and shows them on screen (it might be at that stage that the posting key is being shown as the same as the active key). I am guessing this could be a simple array index missed out.

The broadcasted transaction for debug purposes is here:
https://hiveblocks.com/tx/4d860c696d4dcd8bd7aa9075636ef4f9cd3a48ab

**Comment by 4Ykw** [comment]
Not sure if this is related:

https://github.com/stoodkev/hive-keychain/blob/149d8f70865140eeb94f3ec00529791ced0c9ff6/html/popup.html

https://github.com/stoodkev/hive-keychain/blob/149d8f70865140eeb94f3ec00529791ced0c9ff6/html/popup.html#L200

```
    <div id="master_check" class="hide-at-start">
      <div class="back_add_key back_enabled"></div>
      <p id="import_success"></p>
      <div class="key_checkbox" id="import_posting">
        <label for="posting_key" class="checkbox_container">
          <div class="import_key_title"></div>
          <div class="import_key_info"></div>
          <input type="checkbox" checked="checked" id="posting_key" />
          <span class="checkmark" />
        </label>
      </div>
      <div class="key_checkbox" id="import_active">
        <label for="active_key" class="checkbox_container">
          <div class="import_key_title"></div>
          <div class="import_key_info"></div>
          <input type="checkbox" checked="true" id="active_key" />
          <span class="checkmark" />
        </label>
      </div>
      <div class="key_checkbox" id="import_memo">
        <label for="memo_key" class="checkbox_container">
          <div class="import_key_title"></div>
          <div class="import_key_info"></div>
          <input type="checkbox" checked="true" id="memo_key" />
          <span class="checkmark" />
        </label>
      </div>
      <button id="save_master"></button>
    </div>
```

**Comment by stoodkev** [comment]
![Screen Shot 2021-06-18 at 3 52 10 PM](https://user-images.githubusercontent.com/32375533/122526738-35497d80-d04d-11eb-8f68-3b4396de5a2d.png)

The keys are directly sent by the frontend that makes the request.
In the example above I'm sending a b and c as posting active and memo keys respectively:

Reference for `requestAddAccount` :
https://github.com/stoodkev/hive-keychain#requestaddaccount

Perhaps the dApp you used is passing the wrong key

**Comment by 4Ykw** [comment]
So is it not deducted by the master key? I understood from good-karma that the website was sending only the master password.

**Comment by 4Ykw** [comment]
I have now contacted good-karma. Let's wait until I can get some confirmation from their side.

**Comment by 4Ykw** [comment]
Found it!

https://github.com/ecency/ecency-vision/issues/540

Thanks for the verification @stoodkev
