### ISSUE TITLE
Confirm message for HIVE powerup

### ISSUE THREAD

**Issue by Abwasserrohr** [stoodkev/hive-keychain#99]
Hello there,

I'm frequently using hive keychain to powerup HIVE for contest members. Now the problem for me is that there is no confirm message for powerups and I worry that one day, I power up 1000 HIVE instead of 100 HIVE for example, so it would be great to have a confirm popup like on transfer.

**Comment by stoodkev** [comment]
This has been implemented in the refactored version of our extension which should be live sometime next month.
